### ISSUE TITLE
update favicon to IDC

### ISSUE THREAD

**Issue by pieper** [ImagingDataCommons/IDC-Viewer-Support#9]
[idc-favicons.zip](https://github.com/ImagingDataCommons/IDC-Viewer-Support/files/5247935/idc-favicons.zip)

When you deploy, copy the attached favicon files to replace the corresponding ones in the built `public/assets` directory.

**Comment by wlongabaugh** [comment]
Added these copies to workflow. and assets to repo.

**Comment by wlongabaugh** [comment]
Note the above idc-logo versions were replaced by NCI logo versions.
